Fix var shape
epikjjh/Distributed-Deep-Learning pull request #12
Opened 2020-08-08 10:45 UTC by junan146

- fix var_shape variable of Model.py file
- separate worker class from sync.py to worker.py

2020-08-08 14:28 UTC, epikjjh requested changes

2020-08-08 14:28 UTC, epikjjh commented on mnist/model.py
> +            self.cost = tf.reduce_mean(-tf.reduce_sum(self.y_ * tf.log(self.y), reduction_indices=[1]))
softmax_cross_entropy_with_logits가 더 낫지 않나? 이거 쓰면 value clip 되는 것으로 알고 있어서

2020-08-08 14:28 UTC, epikjjh commented on mnist/model.py
> +            self.layer = [tf.get_variable("v{}".format(i), shape=self.var_shape[i], dtype=tf.float32) for i in range(self.var_size)]
오 이거쓰면 편하네 저 부분 list comprehension으로 나중에 바꿀게

2020-08-08 14:28 UTC, epikjjh commented on mnist/model.py
> +            self.d2 = [np.empty(self.var_shape[i], dtype=np.float32) for i in range(self.var_size)]
이 부분 중복 되는 것 같음. apply_gradients는 ps에서만 수행하는거라 굳이 모델에서 가지고 있을 필요 없을 것 같아
vars, d1, d2는 무슨 역할 하는거야? 이것도 worker 인스턴스에서 만들어 주고 있는 것이라 중복되는 것 같음

2020-08-08 15:35 UTC, junan146 commented on mnist/model.py
> +            self.cost = tf.reduce_mean(-tf.reduce_sum(self.y_ * tf.log(self.y), reduction_indices=[1]))
오케이 하나 배웠다 그렇게 가자

2020-08-08 15:36 UTC, junan146 commented on mnist/model.py
> +            self.layer = [tf.get_variable("v{}".format(i), shape=self.var_shape[i], dtype=tf.float32) for i in range(self.var_size)]
확인

2020-08-08 15:36 UTC, junan146 commented on mnist/model.py
> +            self.d2 = [np.empty(self.var_shape[i], dtype=np.float32) for i in range(self.var_size)]
이부분은 없애도 될 것 같아. 확인하고 보냈어야하는데 수정 다 안된상태로 올렸나보다 쏘리

2020-08-09 09:40 UTC, epikjjh commented
오키 그럼 var_shape부분만 반영할게~

2020-08-09 09:40 UTC, closed without merging